name: bwu_polymer_routing
version: 0.0.1
author: Günter Zöchbauer <guenter@gzoechbauer.com>
description: Some helper classes and components to use route_hierarchical with Polymer.dart.
homepage: https://github.com/bwu-dart/bwu_polymer_routing
environment:
  sdk: '>=1.6.0-0'
dependencies:
  di: '>=2.0.1 <2.1.0'
  polymer: '>=0.12.0+7 <0.13.0'
  route_hierarchical: '>=0.4.21 <0.5.0'
dependency_overrides:
  code_transformers: '>=0.2.0 <0.3.0'
transformers:
- polymer:
    entry_points:
    - example/example_01.html
- di
